### PR TITLE
Olson main2 fixed the function

### PR DESCRIPTION
**Pull request by olsonjac**
Brought to you by google gemini lol

### CODE REVIEW

**Comment by olsonjac** [comment]
Enjoy

**Review by killmaster65 — APPROVED** [review]
Looks awesome! I see that you change the form and the program file

**Comment by olsonjac** [comment]
The routing change was important and worth studying

**Comment by killmaster65** [comment]
Yea it going to allow us to send data where it should go, instead of the route we told it to. PS Sorry didn't mean to close it the computer keyboard still gets me sometimes

**Comment by olsonjac** [comment]
It needs to be merged, not closed

**Comment by killmaster65** [comment]
Okay got it.

**Pull request merged**
